/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_douglas_temperatureapp_JNITempConverter */

#ifndef _Included_com_example_douglas_temperatureapp_JNITempConverter
#define _Included_com_example_douglas_temperatureapp_JNITempConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_douglas_temperatureapp_JNITempConverter
 * Method:    convertCToF
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_douglas_temperatureapp_JNITempConverter_convertCToF
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
